### ISSUE TITLE
Adding a template for users to be able to click on other user's profile and see their posts and pictures

### ISSUE THREAD

**Issue by ShahidKhhan** [KaylaCharky/SOEN-341#36]
User story: As a user, I should be able to click on another user's profile and be able to see their posts and pictures.

Risk: high
points: 7/10
Acceptance testing: The story is considered to be finished if user1 clicks on user2's profile and is able to see user2's posts and pictures.

**Comment by KaylaCharky** [comment]
just missing formatting but finished in theory
